BaseUrl = "https://torablog.netlify.com/"
LanguageCode = "ja"
defaultContentLanguage = "ja"
Title = "Tora Blog"
paginate = 10
Copyright = "All posts are licensed under <a href='https://creativecommons.org/publicdomain/zero/1.0/'>CC0</a>."
canonifyurls = true
sectionPagesMenu = "main"
hasCJKLanguage = true
pygmentsCodeFences = true
theme = "mytheme"

[params]
  description = "技術とかいろいろ"
  logo = "avatar.png"
  author = "Torajiro Aida"
  authorname = "Torajiro Aida"
  authorlocation = "Japan"
  authorwebsite = "https://github.com/aidatorajiro/"
  authorbio = ""
