BaseUrl = "https://torablog.netlify.com/"
LanguageCode = "ja"
Title = "Tora Blog"
paginate = 10
Copyright = "All posts are licensed under CC0."
canonifyurls = true
theme = "hugo-theme-casper"
sectionPagesMenu = "main"
hasCJKLanguage = true

[params]
  description = "技術とかいろいろ"
  cover = "avatar.png"
  author = "Torajiro Aida"
  authorname = "Torajiro Aida"
  authorlocation = "Japan"
  authorwebsite = "https://torablog.netlify.com/"
  authorbio = "Japanese high school student"
  githubName = "aidatorajiro"
  facebookName = "kawarusosu"
  twitterName = "kawarusosu"
  hideHUGOSupport = false
  googleAnalyticsUserID = "UA-111453747-1"
  customCSS = ["css/custom.css"]
  
  logo = "avatar.png"
  
  [params.social]
    twitter = "kawarusosu"