BaseUrl = "https://torablog.netlify.com/"
Title = "Tora Blog"
paginate = 10
DisqusShortname = "tora-blog"
Copyright = "All posts are licensed under CC0."
canonifyurls = true
theme = "hugo-theme-casper"
sectionPagesMenu = "main"

[params]
  description = "技術とかいろいろ"
  cover = "avatar.png"
  author = "Torajiro Aida"
  githubName = "aidatorajiro"
  facebookName = "kawarusosu"
  twitterName = "kawarusosu"
  hideHUGOSupport = false
  googleAnalyticsUserID = "UA-111453747-1"
  
  [params.social]
    twitter = "kawarusosu"