BaseUrl = "https://torablog.netlify.com/"
LanguageCode = "ja-jp"
Title = "Tora Blog"
paginate = 10
# DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All posts are licensed under CC0."
canonifyurls = true
theme = "hugo-theme-casper"

[params]
  description = "技術とかいろいろ"
  cover = "avatar.png"
  author = "Torajiro Aida"
  githubName = "aidatorajiro"
  twitterName = "kawarusosu"
  hideHUGOSupport = false
  # hjsStyle = "default"

  customCSS = [ "syntax.css" ]
  
  [params.social]
    twitter = "kawarusosu"