baseurl = "https://torablog.netlify.com/"

languageCode = "ja-jp"

title = "Tora Blog"

theme = "hugo-now"

googleAnalytics = ""

copyright = "All posts are licensed under [CC0](https://creativecommons.org/publicdomain/zero/1.0/deed.en)."

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "技術とかいろいろ"
  author = "Torajiro Aida"
  keywords = []
  avatar = "avatar.png"
  displayauthor = false

  # pygments
  PygmentsCodeFences = true
  pygmentsCodeFencesGuessSyntax = true
  pygmentsStyle = "monokai"
  pygmentsUseClasses = true

  # pagination
  paginate = 10
  paginatePath = "page"