name = "Casper"
license = "CC0"
licenselink = "https://github.com/aidatorajiro/torablog/blob/master/LICENSE.md"
description = "TORA BLOG THEME!!!"
homepage = "https://torablog.netlify.app/"
tags = ["blog"]
features = [""]
min_version=0.1.0

[author]
  name = "Torajiro Aida"
  homepage = "https://torablog.netlify.app/"

